#!/bin/bash

if [ -x /usr/bin/yum ]; then
    yum install git ruby rubygems ruby-devel gcc  -y 
else
    apt-get update && apt-get install git ruby1.9.1 ruby1.9.1-dev rubygems1.9.1 build-essential -y
    update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby1.9.1 400
    update-alternatives --set gem /usr/bin/gem1.9.1
fi

curl -sL https://www.opscode.com/chef/install.sh | bash /dev/stdin -v 11.12.8-2

export PATH=$PATH:/usr/local/bin

git config --global user.email "support@elasticbox.com"
git config --global user.name "ElasticBox support"

if [[ ! -d $folder/cookbooks ]]; then
    mkdir -p $folder/cookbooks
    cd $folder/cookbooks
    git init
    echo "cookbooks" > cookbooks
    git add .
    git commit -a -m "cookbooks first commit"
fi

cookbooks=$(curl -ks $COOKBOOK_LIST | sed 's/#.*//g')

for cookbook in $cookbooks
do
    knife cookbook site install $(echo $cookbook | tr '=' ' ') --cookbook-path $folder/cookbooks
done

if [[ $? -eq 100 ]]; then exit 0; fi
