#!/bin/bash

gpg --keyserver pgpkeys.mit.edu --recv-key 9B7D32F2D50582E6
gpg --armor --export 9B7D32F2D50582E6 | apt-key add -
curl -ks https://jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list

apt-get -y update
apt-get -y --force-yes install jenkins nginx git
