#!/bin/bash

set -e

apt-get -y update
apt-get -y install python-software-properties software-properties-common

add-apt-repository -y ppa:webupd8team/java
apt-get -y update
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
apt-get -y install oracle-java8-installer

curl -kSL https://s3-us-west-2.amazonaws.com/ebx-deb-packages/elasticsearch-{{ VERSION }}.deb -o {{ folder }}/elasticsearch-{{ VERSION }}.deb
dpkg --force-confold --install {{ folder }}/elasticsearch-{{ VERSION }}.deb
rm {{ folder }}/elasticsearch-{{ VERSION }}.deb

update-rc.d elasticsearch defaults 95 10
