#!/bin/bash -e

# Set slave password
if [ -z "{{ SLAVE_PASSWORD }}" ]; then
    elasticbox set "SLAVE_PASSWORD" "$(date +%s | sha256sum | base64 | head -c 32)"
fi


# Set server id
if [ -z "{{ SERVER_ID }}" ]; then
    elasticbox set "SERVER_ID" "$(shuf -i 0-4294967295 -n 1)"
fi
