#!/bin/bash

set -e

apt-get -y update
apt-get -y install python-software-properties software-properties-common

add-apt-repository ppa:webupd8team/java -y

apt-get -y update
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
apt-get -y install oracle-java8-installer

curl -ksL https://s3-us-west-2.amazonaws.com/ebx-deb-packages/logstash_{{ VERSION }}-1_all.deb -o {{ folder }}/logstash_{{ VERSION }}-1_all.deb
dpkg --install --force-confold {{ folder }}/logstash_{{ VERSION }}-1_all.deb
rm {{ folder }}/logstash_{{ VERSION }}-1_all.deb

# Stop not required logstash-web
service logstash-web stop || true
rm -f /etc/init/logstash-web.conf /etc/init.d/logstash-web

HOST_NAME="$(hostname)"
elasticbox set HOSTNAME "$HOST_NAME"
