#!/bin/bash

# Download config.json
curl -ks $CONFIG | elasticbox config -o /opt/couchbase-sync-gateway/config.json

/opt/couchbase-sync-gateway/bin/sync_gateway /opt/couchbase-sync-gateway/config.json &