#!/bin/bash

if [ -x /usr/bin/yum ]; then
    yum -y install sqlite-devel
else
    apt-get -y install sqlite3
    apt-get -y install libsqlite3-dev
fi
gem install bundler --no-ri --no-rdoc --version "=1.3.6"